# Generated by Django 5.0.7 on 2024-10-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_county_servicecategories_remove_service_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Public University', 'Public University'), ('Private Universities', 'Private University'), ('Technical and Vocational Education and Training Institutions (TVET)', 'Technical and Vocational Education and Training Institutions (TVET)'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Primary', 'Primary')], default='institution_categories', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='duration_in_weeks',
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='duration_in_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='services.institution'),
        ),
    ]
