# Generated by Django 5.0.7 on 2024-10-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_institution_remove_trainingprogram_duration_in_weeks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, related_name='training_programs', to='services.skill'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
